FIX: add BUILD_DIR to detect script

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,15 +1,17 @@
 #!/usr/bin/env bash
 # usage: bin/detect BUILD_DIR
 
+BUILD_DIR="$1"
+
 /app/.awscli/bin/aws --version &>/dev/null || {
   echo "ERROR: aws-cli is not installed. please add heroku-buildpack-awscli" >&2
   exit 1
 }
 
-# [ -d "$BUILD_DIR/public/assets" ] || {
-#   echo "ERROR: public/assets directory not found, have assets been compiled?" >&2
-#   exit 1
-# }
+[ -d "$BUILD_DIR/public/assets" ] || {
+  echo "ERROR: public/assets directory not found, have assets been compiled?" >&2
+  exit 1
+}
 
 # Since Heroku does not pass to the detect script the ENV_DIR, we cannot detect
 # whether the CDN_HOST environment variable is present.
